### ISSUE TITLE
请问下， 配置密钥在哪里配置呢

### ISSUE THREAD

**Issue by gyp719** [asundust/dcat-auth-captcha#10]
在哪里配置呢？ 显示 验证码页面 是需要在前端页面加入吗？

**Comment by asundust** [comment]
![image](https://github.com/asundust/dcat-auth-captcha/assets/6573979/75e3af4d-93b2-4366-853f-c19905ebd51f)
Dact Admin的所有配置项目都是在网页端进行的啊，以上截图是官方Demo的截图。

**Comment by gyp719** [comment]
我在后台系统 扩展 启动。 登录页面显示 

<img width="1176" alt="image" src="https://github.com/asundust/dcat-auth-captcha/assets/30563368/87ee2f5f-0c32-4930-a664-80628f7d87e2">

是否在哪里需要进行配置密钥？

**Comment by asundust** [comment]
先卸载扩展包，确保登陆后，再安装，配置。

**Comment by gyp719** [comment]
> 先卸载扩展包，确保登陆后，再安装，配置。

可以了，感谢大佬的指导。

<img width="627" alt="image" src="https://github.com/asundust/dcat-auth-captcha/assets/30563368/d0b77277-7192-4e69-ad9d-4fd686d0662b">

**Comment by gyp719** [comment]
想请问下， 在后台设置的密钥， 是存储在哪呢？ 数据库中没有进行存储的

**Comment by asundust** [comment]
是存数据库的，如果我没记错是[这行代码](https://github.com/jqhph/dcat-admin/blob/f8ef27cc4d6a79dc346f89d0efb925d4e28ee763/database/migrations/2020_09_07_090635_create_admin_settings_table.php#L24)

**Comment by gyp719** [comment]
> 是存数据库的，如果我没记错是[这行代码](https://github.com/jqhph/dcat-admin/blob/f8ef27cc4d6a79dc346f89d0efb925d4e28ee763/database/migrations/2020_09_07_090635_create_admin_settings_table.php#L24)

非常感谢。 找到了。谢谢大佬。
