### ISSUE TITLE
安装失败 not match the constraint

### ISSUE THREAD

**Issue by izqx** [asundust/dcat-auth-captcha#3]
`composer require asundust/dcat-auth-captcha
Using version ^2.0 for asundust/dcat-auth-captcha
./composer.json has been updated
Running composer update asundust/dcat-auth-captcha
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires asundust/dcat-auth-captcha ^2.0 -> satisfiable by asundust/dcat-auth-captcha[2.0.0].
    - asundust/dcat-auth-captcha 2.0.0 requires guzzlehttp/guzzle ^6.3 -> found guzzlehttp/guzzle[7.3.0] but it does not match the constraint.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.`
![图片](https://user-images.githubusercontent.com/33259989/117394267-6f8d0e80-af28-11eb-95a9-af399a0850cf.png)

**Comment by asundust** [comment]
@izqx 已处理 请更新至2.0.1版本

**Comment by izqx** [comment]
> 
> 
> @izqx 已处理 请更新至2.0.1版本

ok
