### ISSUE TITLE
滑块验证未通过

### ISSUE THREAD

**Issue by izqx** [asundust/dcat-auth-captcha#4]
用的是顶象的验证，平时是**滑动拼图验证**但**有时候**滑块验证通过后又会弹出一个**文字点选验证**，这个验证通过后虽然页面显示**验证成功**，但点击登录后会提示验证失败
![图片](https://user-images.githubusercontent.com/33259989/117422368-1934c580-af52-11eb-8c53-49a10ba35f70.png)

![图片](https://user-images.githubusercontent.com/33259989/117421915-99a6f680-af51-11eb-8543-5e5fcbb2db1b.png)

![图片](https://user-images.githubusercontent.com/33259989/117421879-8dbb3480-af51-11eb-9382-86bf6f2a633d.png)
![图片](https://user-images.githubusercontent.com/33259989/117422877-ad069180-af52-11eb-8d0d-6ae83c2b8d42.png)

![图片](https://user-images.githubusercontent.com/33259989/117422812-9bbd8500-af52-11eb-9c5d-a4329ca3d1fb.png)

**Comment by asundust** [comment]
@izqx 配置参数都在后台填写了吗?

**Comment by izqx** [comment]
> 
> 
> @izqx 配置参数都在后台填写了吗?
顶象的配置不就这三个吗？
![图片](https://user-images.githubusercontent.com/33259989/117423499-61081c80-af53-11eb-87f5-71bb8e177200.png)
![图片](https://user-images.githubusercontent.com/33259989/117423536-69f8ee00-af53-11eb-9161-83894505c5b7.png)
只有一个滑块时是可以通过的，再弹出一个点选验证就通过不了

**Comment by asundust** [comment]
@izqx 我这边先用你的密钥测试一下 测试完成后 建议重置一下密钥 你的密钥暴露了

**Comment by izqx** [comment]
> 
> 
> @izqx 我这边先用你的密钥测试一下 测试完成后 建议重置一下密钥 你的密钥暴露了

8835bd971574fc7ae78656cd8cb615a5

d7d0576a464b90568f99786ac98cc3e7

没事，不扣我钱😀

**Comment by asundust** [comment]
这边测试了一下

> > @izqx 我这边先用你的密钥测试一下 测试完成后 建议重置一下密钥 你的密钥暴露了
> 
> 8835bd971574fc7ae78656cd8cb615a5
> 
> d7d0576a464b90568f99786ac98cc3e7
> 
> 没事，不扣我钱😀

这边测试了一下 是没问题的 我这边顺带测试了每个样式类型的结果 都是没问题 这边根据你的描述怀疑你的机器被拉黑 你尝试一下匿名窗口吧

**Comment by izqx** [comment]
> 
> 
> 这边测试了一下
> 
> > > @izqx 我这边先用你的密钥测试一下 测试完成后 建议重置一下密钥 你的密钥暴露了
> > 
> > 
> > 8835bd971574fc7ae78656cd8cb615a5
> > d7d0576a464b90568f99786ac98cc3e7
> > 没事，不扣我钱grinning
> 
> 这边测试了一下 是没问题的 我这边顺带测试了每个样式类型的结果 都是没问题 这边根据你的描述怀疑你的机器被拉黑 你尝试一下匿名窗口吧

我靠好像是这样的，QQ浏览器一次文字点击都没弹出来过，火狐每次都有，新建隐私窗口就能通过验证了。多谢大佬😀
