### ISSUE TITLE
recaptcha错误

### ISSUE THREAD

**Issue by kevin700523** [asundust/dcat-auth-captcha#5]
recaptcha v2 设定后
登入没有出现核取方块
登入后出现错误

![截圖 2021-05-09 上午12 29 12](https://user-images.githubusercontent.com/16574141/117546631-f099f200-b05d-11eb-903b-024796841b54.png)
![截圖 2021-05-09 上午12 30 20](https://user-images.githubusercontent.com/16574141/117546636-f394e280-b05d-11eb-8fac-cd1573a47e41.png)

**Comment by asundust** [comment]
@kevin700523 这边实测 google v2 隐藏和显示均无该问题 能具体更加细致的查一下嘛?

**Comment by kevin700523** [comment]
抱歉我这边设置错误，已经可以使用 谢谢！
