### ISSUE TITLE
谷歌身份验证器

### ISSUE THREAD

**Issue by ygcool** [asundust/dcat-auth-captcha#8]
大佬能否可以考虑下增加谷歌身份验证器的~  输入动态验证码

**Comment by asundust** [comment]
可以考虑使用这个包？
[ https://packagist.org/packages/ghost/google-authenticator]( https://packagist.org/packages/ghost/google-authenticator)

本来Laravel-Admin的官网有很多三方插件可以自己提交的，现在Laravel-Admin的维护者好像给关了该页面
在packagist上看到该包安装次数挺多的，如有更好的包推荐，可以推荐一下。

**Comment by ygcool** [comment]
这个能直接用于dcat-admin上？

**Comment by asundust** [comment]
尴尬了 我刚刚没注意看到你提的issue是在dcat的包下， 那试试这个？
[https://packagist.org/packages/changzhong/extension-google-authenticator](https://packagist.org/packages/changzhong/extension-google-authenticator)

**Comment by ygcool** [comment]
这个我看了的，是1.0的 目前2.x版本的还没有

**Comment by asundust** [comment]
那我有空看看开发一个吧，不过得另起一个包了

**Comment by ygcool** [comment]
👍🏻期待!

**Comment by laravel920** [comment]
您好，作者。我也很期待，能有一个谷歌验证器登录的。找了一圈，都是不完善的。

**Comment by asundust** [comment]
@ygcool 抱歉，精力不足，现在才搞好  @laravel920 已完成
https://github.com/asundust/dcat-auth-google-2fa
