### ISSUE TITLE
语言无法切换，一直都是英文

### ISSUE THREAD

**Issue by laravel920** [asundust/dcat-auth-captcha#9]
![image](https://user-images.githubusercontent.com/64994491/182551204-523fbb27-559a-4971-943f-2c8a4b20c9f7.png)

**Comment by asundust** [comment]
这边建议查看一下，语言设置是`zh-CN`或者`zh_CN`?

**Comment by laravel920** [comment]
谢谢

**Comment by laravel920** [comment]
![image](https://user-images.githubusercontent.com/64994491/182556918-8817fa08-5648-4392-a1e7-05caac45778a.png)

**Comment by asundust** [comment]
这个情况(不算英文,是找不到翻译文件)我曾经遇到过的,好久了不知道怎么操作就好了的,麻烦复现一下? composer update了吗?

**Comment by laravel920** [comment]
我直接在dcat admin 后台开发工具-扩展-本地安装，导入插件的，不是使用composer 安装。我也composer update也没用，求大神指教。
![image](https://user-images.githubusercontent.com/64994491/182744120-acfb1fd7-9a3a-4efc-a2af-ce99bf94c193.png)
![image](https://user-images.githubusercontent.com/64994491/182744170-b64fc68b-8fca-42d1-8ff0-aeae69321790.png)

**Comment by asundust** [comment]
你试试`composer require asundust/dcat-auth-captcha`安装一下看看？

**Comment by laravel920** [comment]
代码也是有这个文件的哦。
![image](https://user-images.githubusercontent.com/64994491/182744374-4646daf2-8992-4de2-8f5c-fa4ef5077cbd.png)

**Comment by laravel920** [comment]
我试下看看，感谢
